name: main.yml
on:
  push:

permissions:
  id-token: write

jobs:
  job1:
    uses: /luviny/env-loader-test/.github/workflows/job1.yml
    
  job2:
    uses: /luviny/env-loader-test/.github/workflows/job2.yml
    needs: job1
    with:Ï€
      gzip-env-value: ${{ needs.job1.outputs.gzip-env-value }} 
